[workspace]
resolver = "2"
members = [
    "rust/crates/fast-nc-zarr-model",
    "rust/crates/fast-nc-zarr-zarr",
    "rust/crates/fast-nc-zarr-python",
    "apps/desktop/src-tauri",
]

[workspace.package]
version = "1.8.3"
edition = "2021"
rust-version = "1.83"

[workspace.dependencies]
fast-nc-zarr-zarr = { path = "rust/crates/fast-nc-zarr-zarr" }
fast-nc-zarr-model = { path = "rust/crates/fast-nc-zarr-model" }
pyo3 = { version = "0.29", features = ["extension-module"] }
rayon = "1.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
zarrs = "0.23.13"
zarrs_filesystem = "0.3.12"
tauri = { version = "2.11.3" }
tauri-build = { version = "2.6.3" }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
ndarray = "0.17.2"
netcdf = { version = "0.10.5", features = ["static"] }
